export const ROUTES = {
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  projects: '/projects',
  projectNew: '/projects/new',
  projectSettings: (projectId) => `/projects/${projectId}/settings`,
  project: (projectId) => `/projects/${projectId}`,
  requirements: (projectId) => `/projects/${projectId}/requirements`,
  requirement: (requirementId) => `/requirements/${requirementId}`,
  testCases: (projectId) => `/projects/${projectId}/test-cases`,
  testCaseNew: (projectId) => `/projects/${projectId}/test-cases/new`,
  testCase: (testCaseId) => `/test-cases/${testCaseId}`,
  aiGenerator: (projectId) => `/projects/${projectId}/ai-test-generator`,
  testRuns: (projectId) => `/projects/${projectId}/test-runs`,
  testRunNew: (projectId) => `/projects/${projectId}/test-runs/new`,
  testRun: (runId) => `/test-runs/${runId}`,
  defects: (projectId) => `/projects/${projectId}/defects`,
  defectNew: (projectId) => `/projects/${projectId}/defects/new`,
  defect: (defectId) => `/defects/${defectId}`,
  regression: (projectId) => `/projects/${projectId}/regression`,
  automation: (projectId) => `/projects/${projectId}/automation`,
  automationJob: (jobId) => `/automation/jobs/${jobId}`,
  reports: (projectId) => `/projects/${projectId}/reports`,
  releaseReadiness: (projectId) => `/projects/${projectId}/release-readiness`,
  profile: '/settings/profile',
  workspace: '/settings/workspace',
  members: '/settings/members',
  notifications: '/settings/notifications',
  preferences: '/settings/preferences',
}

export const NAV_ITEMS = [
  { to: ROUTES.dashboard, label: 'Dashboard', icon: 'LayoutDashboard' },
  { to: ROUTES.projects, label: 'Projects', icon: 'FolderKanban' },
  { type: 'project', label: 'Requirements', icon: 'ListChecks' },
  { type: 'project', label: 'Test Cases', icon: 'FileCheck2' },
  { type: 'project', label: 'Test Runs', icon: 'PlayCircle' },
  { type: 'project', label: 'Defects', icon: 'Bug' },
  { type: 'project', label: 'Regression Planner', icon: 'GitPullRequestArrow' },
  { type: 'project', label: 'Automation', icon: 'Bot' },
  { type: 'project', label: 'Reports', icon: 'BarChart3' },
  { to: ROUTES.members, label: 'Team & Settings', icon: 'Settings' },
]
